### ISSUE TITLE
Posting to Endpoint with Express using Content-Type: application/json does not emit events to req.on('close')

### ISSUE THREAD

**Issue by elucidsoft** [nestjs/nest#10389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The req.on('close') event is not emitting when the content-type: applicaiton/json header is set. This makes no sense, the content-type header should not change the behavior when the connection is closed.  This use to work, the behavior has somehow changed in  either upgrade 7 or 8.  We just observed this behavior, but we have done several nestjs upgrades and we are not sure when the behavior started.  This took an extremely long time to track down, and is rather critical to our workflow, can please advise a temp workaround for us would be very helpful!!

### Minimum reproduction code

https://github.com/elucidsoft/nestjs-broken-middleware

### Steps to reproduce

1. npm i
2. npm run start:debug

## Working without Header
1. Use insomnia or curl or whatever tool you want to post to the http://localhost:3020/test endpoint, with the `content-type:` header NOT set.
2. Examine console output of 'Inside test', followed by '-- Connection Closed --'
3. Event emitted properly.

## Broken with application/json Content-Type header
1. Use insomnia or curl or whatever tool you want to post to the http://localhost:3020/test endpoint, with the `content-type: application/json` header set.
2. Examing console output of only 'Inside test' but no '-- Connection Closed --'
3. Event did NOT emit properly.

### Expected behavior

Event should emit no matter the content-type set.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.1.4

### Packages versions

```json
  "dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "body-parser": "^1.20.1",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.5.5"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "^28.1.4",
    "@types/node": "^18.0.3",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^5.30.5",
    "@typescript-eslint/parser": "^5.30.5",
    "eslint": "^8.19.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jest": "^28.1.2",
    "prettier": "^2.7.1",
    "source-map-support": "^0.5.21",
    "supertest": "^6.2.4",
    "ts-jest": "^28.0.5",
    "ts-loader": "^9.3.1",
    "ts-node": "^10.8.2",
    "tsconfig-paths": "^4.0.0",
    "typescript": "^4.7.4"
  },
```

I also verified this is broken in 8.x

### Node.js version

16.14.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

I verified this behavior on multiple platforms of Linux, inside docker, and outside docker, with multiple REST clients. All observed same behavior.

**Comment by elucidsoft** [comment]
I added an express version to the repo, so you can run them from same repo to see that express behaves as you would expect, and nestjs is not.

**Comment by micalevisk** [comment]
btw you forgot the call `app.use(bodyParser.json())` in the Express version. But yeah, it does triggers the 'close' event.

**Comment by micalevisk** [comment]
after investigating that a bit, I found this weird(?) behavior:

https://github.com/nestjs/nest/blob/8e3af065bb9abbecc91b4e6068c8e205ef79d165/packages/core/router/router-execution-context.ts#L139-L151

adding 

```js
const onClose = () => console.log('----------')
req.on('close', onClose)
```

right before L149, will make that `onClose` be called. But when we move that line to after L149, `onClose` won't get called. Maybe that's due to how the event loop works or there is something wrong with `RouterExecutionContext#createPipesFn`

**Comment by micalevisk** [comment]
I just tested something: if `fnApplyPipes` no longer returns a Promise, we can make that `handler` sync. If we do so, the `close` event got emitted in controller's method. So I guess that this is something to do on how the event loops works. But the 'end' event still didn't got emitted

**Comment by WiseBird** [comment]
@elucidsoft Were you able to find a workaround for this issue?

**Comment by micalevisk** [comment]
another thing that I observed:

https://github.com/nestjs/nest/blob/15cb568e40f42fb3c40c4cb2ad432b23a5ec7bcd/packages/core/router/router-execution-context.ts#L141-L151

if we drop the `await` from L149 and make `createPipesFn` return a synchronous function, it will work as we expect. But when we add a new line right after L149 using an await like this: `await new Promise((resolve) => setTimeout(resolve, 0));` it will work just the same as having `await` on L149. No ideia why is this tho

**Comment by funfungo** [comment]
I encountered this problem when I try to apply sse request

**Comment by winkcc** [comment]
> I encountered this problem when I try to apply sse request我在尝试应用 sse 请求时遇到了这个问题

I'm facing the same issue. Did you manage to solve it?

**Comment by winkcc** [comment]
> I encountered this problem when I try to apply sse request我在尝试应用 sse 请求时遇到了这个问题

I encountered this problem as well. Have you found a solution?

**Comment by elucidsoft** [comment]
> [@elucidsoft](https://github.com/elucidsoft) Were you able to find a workaround for this issue?

Yes I found a workaround for this so it can probably be closed. It is a bug I guess that some people run into though, so I don't know if you guys want to keep it open. It's pretty easy to get around by just using socket.on instead and I've had the workaround in production for over a year and it works fine fwiw.

**Comment by micalevisk** [comment]
I think we should leave this open as it pretty hidden buggy behavior. I still didn't manage to find a solution for it :/

**Comment by kamilmysliwiec** [comment]
Fixed in the latest version (with express v5)

**Comment by micalevisk** [comment]
Reopening the record on this one rather than the issue — I re-tested on `@nestjs/core@12.0.3` + `express@5.2.1` + `body-parser@2.3.0` + Node 22/26, and `req.on('close')` still does **not** fire when a JSON body is parsed. So this wasn't fixed by Express v5; the close reason above is inaccurate. It is, however, not a Nest bug, and here's the actual mechanism.

By the time your controller method runs, `body-parser` has fully consumed the request stream, so Node has already destroyed the `IncomingMessage` and already emitted `'close'`:

```
state at controller: readableEnded=true complete=true destroyed=true closed=true
```

`'close'` is a one-shot event, so any listener attached after that point can never fire. When there's no body, body-parser doesn't touch the stream, it's still live, and the listener works — that's the `Content-Type` asymmetry that made this so confusing.

Nest's role is only that its pipeline is asynchronous (`await fnCanActivate`, `await fnApplyPipes`, the interceptor chain), so the controller body always runs at least one microtask after the middleware chain. The same thing happens in plain Express with a single `await` and no Nest at all:

```js
app.post('/sync',    async (req, res) => { req.on('close', …) })            // fires
app.post('/awaited', async (req, res) => { await Promise.resolve();
                                           req.on('close', …) })            // never fires
```

This is why we can't "fix" it on our side — it's Node stream lifecycle, and it also explains the "this used to work" (Node's `autoDestroy` behavior changed, not Nest).

Use one of these instead — both fire correctly, including when the client aborts mid-request:

- `res.on('close', …)` — the response object stays alive for the whole exchange
- `req.socket.on('close', …)` — @elucidsoft's workaround, and a sound one
- for `@Sse()` handlers, `@SseSignal()` (available since v11.2.0) gives you an `AbortSignal` that aborts on disconnect — @funfungo, that covers your case

Keeping this closed — as not planned rather than completed, since there's nothing for us to fix — and I'll get the disconnect-detection guidance into the docs since `req.on('close')` is an easy trap to fall into.
