### ISSUE TITLE
[discussion]: improve the ``Controller`` annotation to becomme truly object-oriented

### ISSUE THREAD

**Issue by tulayang** [nestjs/nest#1802]
Hello and a suggestion about ``Controller``.

``Controller`` is really useless in the real programming world, especially to handle **RESTful** routes. For example, a blog application has roughly the following requests:

Request|Method|Url
----|------|----
list blogs|**GET**|`/blogs`
create a blog|**POST**|`/blogs`
delete a blog|**DELETE**|`/blogs/:id`
show a blog|**GET**|`/blogs/:id`
update the title of a blog|**PUT**|`/blogs/:id/title`
update the content of a blog|**PUT**|`/blogs/:id/content`

## Current solution

Currently, you have to write 4 classes:

```ts
@Controller('blogs')
export class BlogsController {
  @Get()
  list(): string {}

  @Post()
  create(): void {}
}

@Controller('blogs/:id')
export class BlogController {
  @Delete()
  delete(): void {}

  @Get()
  show(): string {}
}

@Controller('/blogs/:id/title')
export class BlogTitleController {
  @Put()
  updateTitle(): void {}
}

@Controller('/blogs/:id/content')
export class BlogContentController {
  @Put()
  updateContent(): void {}
}
```

This makes the code weird. And this has no object-oriented taste. Because the methods of the ``Controller`` class are isolated from each other, there is no side effect between them.

## Improved solution

So, can we make the ``Controller`` class looks like more object oriented? A ``Controller`` a route.

Just like:

```ts
@Controller('Get', 'blogs')
export class ListBlogsController {
  onResponse() {}
}

@Controller('Post', 'blogs')
export class CreateBlogController {
  onResponse() {}
}

// ...
```

Then we can extend these classes to append more hook methods to becomme truly object-oriented:

```ts
@Controller('Post', 'blogs')
export class MyCreateBlogController extends CreateBlogController {
  private title: string = ""
  private content: string = ""

  onSessionCheck(): boolean {}

  onValidate(): boolean {
    // validate req.body.title and req.body.content 
    // return false if validate failure
    ...

    this.title = req.body.title;
    this.content = req.body.content ;
    return true;
  }

  onSave() {
    this.mysql.save(this.title, this.content);
  }

  onResponse() {}
}
```

This has several advantages: 

1. Each ``Controller`` class represents a route (request - to - response)

2. The session check, data validation, storage, and response for each request can be written in separate methods. 

3. Each method can be tested separately.

**Comment by kamilmysliwiec** [comment]
Why did you assume that 4 controller classes are required? You could even put all these routes in a single controller if you want to.

> The session check, data validation, storage, and response for each request can be written in separate methods.

Most of these things should be solved at either interceptor/guard/pipe level (not controller).

> Each method can be tested separately.

They can be tested separately anyway :)

**Comment by tulayang** [comment]
@kamilmysliwiec 

>  You could even put all these routes in a single controller if you want to.

That can only use one path and lose the semantics of RESTful. `GET /blogs/:id/title`, `PUT /blogs/:id/title`, `GET /blogs` looks more expressive.


> Most of these things should be solved at either interceptor/guard/pipe level (not controller).

I just think this will provide a flexible interface, no other reason.

**Comment by kamilmysliwiec** [comment]
> That can only use a single path and lose the semantics of RESTful. GET /blogs/:id/title, PUT /blogs/:id/title, GET /blogs, PUT /users/:id/password, PUT /users/:id/avatar looks more expressive.

You can use 1 controller and still have all these routes defined easily within one class :) Keep in mind that `@Get()`, `@Post()` etc decorators can take parameters as well. For instance, `@Get(':id/title')` is fully valid.

**Comment by tulayang** [comment]
I see. But I still feel a little weird. `/users/:id/blogs` and `/users/:id`  have to be in a same `Controller`, however  `/users/:id/blogs` repensents blogs. 

Anyway, never mind.

**Comment by jtmthf** [comment]
@tulayang They still don't have to be in the same controller. This is how I'd organize the two routes.

```ts
// inside user module

@Controller('users')
export class UserController {
	constructor(private readonly userService: UserService) {}

	@Get(':id')
	getUser(@Param('id') id) {
		return this.userService.findById(id);
	}
}
```

```ts
// inside blog module

@Controller('users/:id/blogs')
export class UserBlogController {
	constructor(private readonly blogService: BlogService) {}

	@Get()
	getUserBlogs(@Param('id') id) {
		return this.blogService.findBlogsByUserId(id);
	}
}
```

**Comment by underfisk** [comment]
I agree with @kamilmysliwiec that you can use 1 controller for all but one thing to keep in mind is that controllers is part of MVC pattern which is the same of modifying a Restful state or making it in a different way.
Another thing you can do is create a single controller and that will redirect to object handlers and there you can get it the way you want

**Comment by kamilmysliwiec** [comment]
Note: keeping them in a one controller shouldn't be considered as a best practice :) I have just said that there are no technical limitations that would prevent from doing this.

**Comment by tulayang** [comment]
Sure.

**Comment by underfisk** [comment]
> Keeping them in a one controller shouldn't be considered as a best practice

Truly agree with you
