### ISSUE TITLE
An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by ghiscoding** [nestjs/nest#3513]
## Potential Commit/PR that introduced the regression**

I don't know what introduced this issue, the only thing I found is this Stack Overflow [question](https://stackoverflow.com/questions/58802463/types-sequelize-error-ts1086-an-accessor-cannot-be-declared-in-ambient-context) which says this 

> so presumably sequelize was compiled with typescript 3.7 and emits definition files that previous versions don't understand. So you'll need to upgrade to typescript 3.7 or use an earlier version of sequelize.

But I'm already using TypeScript version `3.7.2`, so I'm not sure where this error comes from and how to fix it.

## Describe the regression

I get a bunch of TypeScript lint errors after updating to latest NestJS `6.10.4` (from `6.10.1`). I tried going back to `~6.10.1` but I still get the error. I tried upgrading my NodeJS version 10 to 12 but still have the same issue. I also tried using TypeScript version `3.6.3` instead of `3.7.2` but still the issue persist.

I found this [bugfix](https://github.com/bokuweb/re-resizable/pull/154/files) in another library, which removes the `get` prefix in `*.d.ts` files, the change is that lib is the following
```diff
-  get size(): Size;
+  size: Size;
```
If I click and follow the link on the first `@nestjs/common/http/http.service.d.ts:13:9` error, I do see the `get` in that `d.ts` file
```ts
export declare class HttpService {
   //...
   get axiosRef(): AxiosInstance;
}
```
So it seems that the `d.ts` Type files are not compiled properly? If I manually remove the `get` from `axiosRef(): AxiosInstance;`, I get 1 less error. So that seems to be the issue.
```diff
export declare class HttpService {
   //...
-   get axiosRef(): AxiosInstance;
+   axiosRef(): AxiosInstance;
}
```

After manually editing every `d.ts` file causing errors and removing their get/set I'm back to working again, so that seems to be the issue.

## Environment
<pre><code>
Nest version: 6.10.1 -> 6.10.4

For Tooling issues:
- Node version: 12.13.1
- TypeScript version: 3.7.2
- Platform:  Windows

Others:

</code></pre>

The errors I get are the following
<pre>
node_modules/@nestjs/common/http/http.service.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.
13     get axiosRef(): AxiosInstance;
           ~~~~~~~~

node_modules/@nestjs/core/helpers/http-adapter-host.d.ts:21:9 - error TS1086: An accessor cannot be declared in an ambient context.
21     set httpAdapter(httpAdapter: T);
           ~~~~~~~~~~~

node_modules/@nestjs/core/helpers/http-adapter-host.d.ts:28:9 - error TS1086: An accessor cannot be declared in an ambient context.
28     get httpAdapter(): T;
           ~~~~~~~~~~~

node_modules/@nestjs/core/injector/container.d.ts:16:9 - error TS1086: An accessor cannot be declared in an ambient context.
16     get applicationConfig(): ApplicationConfig | undefined;
           ~~~~~~~~~~~~~~~~~

node_modules/@nestjs/core/injector/instance-wrapper.d.ts:32:9 - error TS1086: An accessor cannot be declared in an ambient context.
32     get id(): string;
           ~~

node_modules/@nestjs/core/injector/instance-wrapper.d.ts:33:9 - error TS1086: An accessor cannot be declared in an ambient context.
33     set instance(value: T);
           ~~~~~~~~

node_modules/@nestjs/core/injector/instance-wrapper.d.ts:34:9 - error TS1086: An accessor cannot be declared in an ambient context.
34     get instance(): T;
           ~~~~~~~~

node_modules/@nestjs/core/injector/instance-wrapper.d.ts:35:9 - error TS1086: An accessor cannot be declared in an ambient context.
35     get isNotMetatype(): boolean;
           ~~~~~~~~~~~~~

node_modules/@nestjs/core/injector/instance-wrapper.d.ts:36:9 - error TS1086: An accessor cannot be declared in an ambient context.
36     get isTransient(): boolean;
           ~~~~~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:20:9 - error TS1086: An accessor cannot be declared in an ambient context.
20     get id(): string;
           ~~

node_modules/@nestjs/core/injector/module.d.ts:21:9 - error TS1086: An accessor cannot be declared in an ambient context.
21     get scope(): Type<any>[];
           ~~~~~

node_modules/@nestjs/core/injector/module.d.ts:22:9 - error TS1086: An accessor cannot be declared in an ambient context.
22     get providers(): Map<any, InstanceWrapper<Injectable>>;
           ~~~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:23:9 - error TS1086: An accessor cannot be declared in an ambient context.
23     get imports(): Set<Module>;
           ~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:27:9 - error TS1086: An accessor cannot be declared in an ambient context.
27     get relatedModules(): Set<Module>;
           ~~~~~~~~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:31:9 - error TS1086: An accessor cannot be declared in an ambient context.
31     get components(): Map<string, InstanceWrapper<Injectable>>;
           ~~~~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:35:9 - error TS1086: An accessor cannot be declared in an ambient context.
35     get routes(): Map<string, InstanceWrapper<Controller>>;
           ~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:36:9 - error TS1086: An accessor cannot be declared in an ambient context.
36     get injectables(): Map<string, InstanceWrapper<Injectable>>;
           ~~~~~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:37:9 - error TS1086: An accessor cannot be declared in an ambient context.
37     get controllers(): Map<string, InstanceWrapper<Controller>>;
           ~~~~~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:38:9 - error TS1086: An accessor cannot be declared in an ambient context.
38     get exports(): Set<string | symbol>;
           ~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:39:9 - error TS1086: An accessor cannot be declared in an ambient context.
39     get instance(): NestModule;
           ~~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:40:9 - error TS1086: An accessor cannot be declared in an ambient context.
40     get metatype(): Type<any>;
           ~~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:41:9 - error TS1086: An accessor cannot be declared in an ambient context.
41     get distance(): number;
           ~~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:42:9 - error TS1086: An accessor cannot be declared in an ambient context.
42     set distance(value: number);
</pre>

**Comment by ghiscoding** [comment]
Also if it helps, here is my `tsconfig.json` file

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "module": "esnext",
    "skipLibCheck": true,
    "typeRoots": [
      "./node_modules/@types"
    ],
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "target": "es5",
    "lib": [
      "es2015",
      "dom"
    ],
    "moduleResolution": "node",
    "baseUrl": "src",
    "resolveJsonModule": true,
    "allowJs": true
  },
  "include": [
    "./src/**/*.ts",
    "./test/**/*.ts",
    "./types/**/*.d.ts"
  ],
  "atom": {
    "rewriteTsconfig": false
  }
}
```

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by ghiscoding** [comment]
I tried replicating the issue on my other desktop and it was all working, however I had to install NestJS CLI because it was never installed on that computer. That made me think to update the CLI on the computer I had issue with... and after updating to latest NestJS CLI, the error is gone. 

Since I can't replicate after updating NestJS CLI, I'll close the issue
Thanks

**Comment by kotuadam** [comment]
I am having the same problem... Fresh install and updating cli does not solve it. Operating system is Mac OS

**Comment by ghiscoding** [comment]
@kotuadam 
There's couple things you can try, the first one is to delete the entire `node_modules` and also the yarn/npm lock files, then re-install everything. The other options would be to see which TypeScript version you're using, I'm on `3.7.2` which is the latest.

**Comment by syukirah** [comment]
I'm also facing the same problem. Its working in my local but failed when i deploy to server (openshift)

**Comment by Figments** [comment]
Same issue here.

**Comment by whitebyte** [comment]
This issue is relevant, please reopen. I just encountered the same error while trying to update from 6.7.2 to 6.10.4. Managed to resolve it somehow after wiping node_modules and doing `npm upgrade`, but no idea how to reproduce it.

**Comment by kamilmysliwiec** [comment]
It sounds like a breaking change introduced in TypeScript https://github.com/microsoft/TypeScript/issues/33939

**Comment by jeffminsungkim** [comment]
`@nestjs/core v6.10.4`

<img width="606" alt="Screenshot 2019-12-02 17 53 00" src="https://user-images.githubusercontent.com/6092023/69946855-bf93c480-152f-11ea-9626-73357e90f3c2.png">

`@nestjs/core v6.10.2`

<img width="629" alt="Screenshot 2019-12-02 18 05 10" src="https://user-images.githubusercontent.com/6092023/69946877-c8849600-152f-11ea-9623-60dc009d24cd.png">

`Currently using Typescript v3.5.1`

**Comment by Figments** [comment]
Switching entirely to Yarn seems to have fixed the issue for me, though the reason why NPM seemed to be the cause of my specific issues is beyond me.

**Comment by franzos** [comment]
I've been able to resolve this, by manually upgrading typescript. 

`package.json`: `"typescript": "3.4.3"` to `"typescript": "3.7.2"`

finally, cleared out, and re-installed everything:

```
rm -r node_modules; rm package-lock.json
npm install
```

**Comment by kamilmysliwiec** [comment]
I've published v6.10.5 release with a downgraded TypeScript to `3.6.4` version. If you are facing this issue, please, update to the latest version of `@nestjs`. Hopefully, TypeScript team will solve this shortly

**Comment by kotuadam** [comment]
latest push fixed everything for me

**Comment by electron36** [comment]
Facing this issue when adding @nestjs/ng-universal to Angular 8 project.
Have tried with latest Nestjs version 6.10.9 and with Typescript 3.5.3. I am not able to upgrade typescript to newer version, Angular CLI does not support > 3.6.0

Application starts up normal but errors persists.

`10% building 3/3 modules 0 activenode_modules/@nestjs/common/http/http.service.d.ts:13:9 - error TS1086: An accessor cannot be declared in an ambient context.

13     get axiosRef(): AxiosInstance;
           ~~~~~~~~

node_modules/@nestjs/core/helpers/http-adapter-host.d.ts:21:9 - error TS1086: An accessor cannot be declared in an ambient context.

21     set httpAdapter(httpAdapter: T);
           ~~~~~~~~~~~

node_modules/@nestjs/core/helpers/http-adapter-host.d.ts:28:9 - error TS1086: An accessor cannot be declared in an ambient context.

28     get httpAdapter(): T;
           ~~~~~~~~~~~

node_modules/@nestjs/core/injector/container.d.ts:18:9 - error TS1086: An accessor cannot be declared in an ambient context.

18     get applicationConfig(): ApplicationConfig | undefined;
           ~~~~~~~~~~~~~~~~~

node_modules/@nestjs/core/injector/instance-wrapper.d.ts:32:9 - error TS1086: An accessor cannot be declared in an ambient context.

32     get id(): string;
           ~~

node_modules/@nestjs/core/injector/instance-wrapper.d.ts:33:9 - error TS1086: An accessor cannot be declared in an ambient context.

33     set instance(value: T);
           ~~~~~~~~

node_modules/@nestjs/core/injector/instance-wrapper.d.ts:34:9 - error TS1086: An accessor cannot be declared in an ambient context.

34     get instance(): T;
           ~~~~~~~~

node_modules/@nestjs/core/injector/instance-wrapper.d.ts:35:9 - error TS1086: An accessor cannot be declared in an ambient context.

35     get isNotMetatype(): boolean;
           ~~~~~~~~~~~~~

node_modules/@nestjs/core/injector/instance-wrapper.d.ts:36:9 - error TS1086: An accessor cannot be declared in an ambient context.

36     get isTransient(): boolean;
           ~~~~~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:20:9 - error TS1086: An accessor cannot be declared in an ambient context.

20     get id(): string;
           ~~

node_modules/@nestjs/core/injector/module.d.ts:21:9 - error TS1086: An accessor cannot be declared in an ambient context.

21     get scope(): Type<any>[];
           ~~~~~

node_modules/@nestjs/core/injector/module.d.ts:22:9 - error TS1086: An accessor cannot be declared in an ambient context.

22     get providers(): Map<any, InstanceWrapper<Injectable>>;
           ~~~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:23:9 - error TS1086: An accessor cannot be declared in an ambient context.

23     get imports(): Set<Module>;
           ~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:27:9 - error TS1086: An accessor cannot be declared in an ambient context.

27     get relatedModules(): Set<Module>;
           ~~~~~~~~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:31:9 - error TS1086: An accessor cannot be declared in an ambient context.

31     get components(): Map<string, InstanceWrapper<Injectable>>;
           ~~~~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:35:9 - error TS1086: An accessor cannot be declared in an ambient context.

35     get routes(): Map<string, InstanceWrapper<Controller>>;
           ~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:36:9 - error TS1086: An accessor cannot be declared in an ambient context.

36     get injectables(): Map<string, InstanceWrapper<Injectable>>;
           ~~~~~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:37:9 - error TS1086: An accessor cannot be declared in an ambient context.

37     get controllers(): Map<string, InstanceWrapper<Controller>>;
           ~~~~~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:38:9 - error TS1086: An accessor cannot be declared in an ambient context.

38     get exports(): Set<string | symbol>;
           ~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:39:9 - error TS1086: An accessor cannot be declared in an ambient context.

39     get instance(): NestModule;
           ~~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:40:9 - error TS1086: An accessor cannot be declared in an ambient context.

40     get metatype(): Type<any>;
           ~~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:41:9 - error TS1086: An accessor cannot be declared in an ambient context.

41     get distance(): number;
           ~~~~~~~~

node_modules/@nestjs/core/injector/module.d.ts:42:9 - error TS1086: An accessor cannot be declared in an ambient context.

42     set distance(value: number);
           ~~~~~~~~

[21:58:20] Found 23 errors. Watching for file changes.`

**Comment by kamilmysliwiec** [comment]
Lets track this here microsoft/TypeScript#33939
