### ISSUE TITLE
Websocket example doesn't work

### ISSUE THREAD

**Issue by andrewbents** [nestjs/nest#371]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

Websocket example doesn't work

## Minimal reproduction of the problem with instructions

I cloned master, installed example 02 dependencies and ran it. When I open ws.html, it says `WebSocket connection to 'ws://localhost:81/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`. Looking at the code, the port should be the default (3000), not 81. If I change it to localhost:3000 it still doesn't work but the error is now `ws.html:4 WebSocket connection to 'ws://localhost:3000/' failed: Connection closed before receiving a handshake response`

## Environment

<pre><code>
Nest version: 4.5.8 (master)

 
For Tooling issues:
- Node version: 6.11.1  
- Platform:  MacOS 10.12.6 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Hi @andrewbents,
Fixed, let's try now.

**Comment by andrewbents** [comment]
@kamilmysliwiec 
the client in `index.html` kind of works, but not in `ws.html` using plain websockets. Am I missing something?

**Comment by kamilmysliwiec** [comment]
To use `ws.html` you need to set up a `ws` adapter (it'll force Nest to use `ws` instead of `socket.io). Full path `/src/common/adapters/ws-adapter.ts`, tutorial https://docs.nestjs.com/websockets/adapter

**Comment by andrewbents** [comment]
@kamilmysliwiec still doesn't work. I use this adapter (`app.useWebSocketAdapter(new WsAdapter());`) and the error is the same

**Comment by fengcen** [comment]
I have the same problem.

**Comment by fengcen** [comment]
@kamilmysliwiec Can you try the `ws` example?

**Comment by vologab** [comment]
@fengcen You should also define port there - https://github.com/nestjs/nest/blob/master/examples/02-gateways/src/events/events.gateway.ts#L12 
`@WebSocketGateway({ port: 3001})`

**Comment by fengcen** [comment]
@vologab  Can I use the same port for http and websocket ?

**Comment by groovybytes** [comment]
not working for me either

**Comment by groovybytes** [comment]
why is it closed?

**Comment by pixartist** [comment]
Still does not work for me

**Comment by yoiang** [comment]
As mentioned by @kamilmysliwiec this fixed it for me:

```js
import { NestFactory } from '@nestjs/core'
import { WsAdapter } from '@nestjs/platform-ws' // <---
import { AppModule } from './app.module'

async function bootstrap() {
  const app = await NestFactory.create(AppModule)
  app.useWebSocketAdapter(new WsAdapter(app)) // <---
  await app.listen(3000)
}
bootstrap()
```

I did not find it necessary to specify a unique port in the WebSocket Gateway definition
