### ISSUE TITLE
Application does not catch 404 Not Found errors

### ISSUE THREAD

**Issue by omer-morad-ni** [nestjs/nest#3950]
## Current behavior
When referring to invalid route in the application I get the express default not found:
`Cannot GET /something-invalid`.
The thing is it doesn't go through any interceptor or filter, it is just returning plain error.
I even tried to remove all the middlewares, filters and interceptor and it does not work.

## Expected behavior
It should return the default json error or the json error which has been configured in the filter

**Comment by omer-morad-ni** [comment]
When removing `app.setGlobalPrefix(APPLICATION_GLOBAL_PREFIX);` it does work, how can I make it work with global prefix as well?

**Comment by kamilmysliwiec** [comment]
Fixed in 6.11.4. Thanks for reporting.

**Comment by omer-morad-ni** [comment]
The last available one in `@nestjs/core` is `6.11.3`

**Comment by kamilmysliwiec** [comment]
https://www.npmjs.com/package/@nestjs/core

**Comment by kamilmysliwiec** [comment]
Version:
![image](https://user-images.githubusercontent.com/23244943/73272158-37a20200-41e2-11ea-9e08-0e24fbb51190.png)

**Comment by omer-morad-ni** [comment]
Sorry, it probably took time to NPM to refresh the package.
Anyways, now I use `/api` as the application prefix, when i go to `http://localhost:8080/api/not-found` i get the error like it has been defined in the interceptor, yay!
But when I go to `http://localhost:8080/another-one` i still get `Cannot GET /another-one` :/
